ecommerce/Blog/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.PostList.as_view(), name="blog_home"),
    path('<slug:slug>/', views.DetailView.as_view(), name="post_detail"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('services/', include('store.urls')),
    path('info/', include('Blog.urls')),

]
# appending to the list to the urlpatterns list and pointing media url to media root this allows the display of images
# in the static folder
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# example http://127.0.0.1:8000/images/t-shirt.jpg

ecommerce/Blog/models.py
from django.db import models
# User class
from django.contrib.auth.models import User

# Create your models here.
STATUS = ((0, "Draft"), (1, "Published"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    image = models.ImageField(null=True, blank=True)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)

    # function for model method image url attribute to prevent errors with image upload without an image url
    @property
    def header_imageURL(self):
        try:
            url = self.image.url
        except:
            url: ''
        return url

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

ecommerce/Blog/views.py
from django.shortcuts import render
from .models import Post
from django.views import generic

# Create your views here.


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('?')
    template_name = 'blog.html'


class DetailView(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

ecommerce/Blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Trident Cloud Solutions</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap cdn -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/journal/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/sandstone/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">

    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/sketchy/bootstrap.min.css"> -->
</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" id="mainNav">
    <div class="container-fluid">
        <a href="{% url 'homepage' %}" class="navbar-brand" >Trident Cloud Solutions</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item text-black">
                    <a class="nav-link" href="{% url 'homepage' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link" href="{% url 'store' %}">Services<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link" href="{% url 'blog_home' %}">Articles<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link" href="{% url 'about' %}">About Us<span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
    <!-- Content Goes here -->
{% endblock content %}
<!-- Footer -->
<footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">Copyright &copy; 2018-2022 Trident Cloud Solutions </p>
</footer>
</body>

</html>

ecommerce/Blog/templates/blog.html
{% extends "base.html" %}

{% load blog_extras %}

{% block content %}
    <header class="masthead">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h3 class=" site-heading my-4 mt-3 text-black">Solutions for the Cloud Future</h3>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in post_list %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{ post.title }}</h2>
                            {% if post.image %}
                            <img class="thumbnail" src="{{post.header_imageURL}}">
                            {% endif %}
                            <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                            <p class="card-text">{{post.content|slice:":200"|convert_markdown|safe}}</p>
                            <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% block sidebar %}
                {% include 'sidebar.html' %}
            {% endblock sidebar %}
        </div>
    </div>
{%endblock%}

ecommerce/Blog/templates/post_detail.html
{% extends 'base.html' %}
{% load blog_extras %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 card mb-4  mt-3 left  top">
                <div class="card-body">
                    <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
                    <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
                    {% if post.image %}
                        <img class="img-refactor" src="{{post.header_imageURL}}">
                    {% endif %}
                    <p class="card-text ">{{ object.content | convert_markdown | safe }}</p>
                </div>
            </div>
{#            {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}#}
        </div>
    </div>

{% endblock content %}

ecommerce/Blog/templates/sidebar.html
{% block sidebar %}

    <style>
        .card {
            box-shadow: 0 16px 48px #6a6a6b;
        }
    </style>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4 float-right">
        <div class="card my-4.7.">
            <h5 class="card-header">About Me</h5>
            <div class="card-body">
                <p class="card-text">  </p>
                <a href="https://phillipbates.com" class="btn btn-danger">Visit Website!</a>
            </div>
        </div>
    </div>

{% endblock sidebar %}